### PR TITLE
Update spotify.py

### PR DESCRIPTION
**Pull request by daniix**
Add protection against wrong formed tracks when parsing playlists.

### CODE REVIEW

**Comment by weskerfoot** [comment]
Thank you for the contribution, this looks ok to me. Can you give an example of the track ID that was breaking it for you, just so I have an idea of what spotify is doing?

**Comment by weskerfoot** [comment]
Also I think it would be a good idea to use 
```python
sys.stderr.write("Error parsing track {0}".format(track["track"]["id"]))
````

Instead of just printing it.

**Comment by weskerfoot** [comment]
Included this in https://github.com/weskerfoot/Spotify-MPD-Sync/pull/5

Thanks!

**Comment by daniix** [comment]
> Thank you for the contribution, this looks ok to me. Can you give an example of the track ID that was breaking it for you, just so I have an idea of what spotify is doing?

Hi, in my case the track['track'] was empty at a certain point, that was reason of the crash.

**Comment by daniix** [comment]
> Also I think it would be a good idea to use
> 
> ```python
> sys.stderr.write("Error parsing track {0}".format(track["track"]["id"]))
> ```
> 
> Instead of just printing it.

if  track['track'] is empty this print is going to crash as well, right?

**Comment by daniix** [comment]
> > Thank you for the contribution, this looks ok to me. Can you give an example of the track ID that was breaking it for you, just so I have an idea of what spotify is doing?
> 
> Hi, in my case the track['track'] was empty at a certain point, that was reason of the crash.

Many thanks to you in the first place! Your workaround works perfect to me :-)

**Comment by weskerfoot** [comment]
> > Thank you for the contribution, this looks ok to me. Can you give an example of the track ID that was breaking it for you, just so I have an idea of what spotify is doing?
> 
> Hi, in my case the track['track'] was empty at a certain point, that was reason of the crash.

That's interesting. I guess that is a bug on the Spotify side. I didn't expect it to ever return null tracks like that. I won't assume they're not empty then.

**Pull request closed without merging**
